#SPDX-License-Identifier: MIT-0
---
# tasks file for container_CD
#
- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  notify:
    - Log in to registry
    - Pull latest image
    - Log out of registry
    - Start updated container

- name: Remove dangling images
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: true
